version: '3.8'

services:
  backend:
    image: golang:1.20
    restart: always
    environment:
      DB_URI: mongodb://lemonday:pURYBCfteUst7U1d4HraggSeJRLTECIebTRyWQWvhMpioxhgTPrPyBtUBHym93D23aqDC2R0eqCYACDbykF6DA==@lemonday.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@lemonday@
      DB_NAME: demo
      DB_COLLECTION_NAME: todos

  frontend:
    depends_on:
      - backend
    image: node:lts-slim
    ports:
      - 8080:3000
    restart: always
